# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable AndroidX
android.useAndroidX=true

# Kotlin Code Style
kotlin.code.style=official

# Compose
android.enableCompose=true

# Enable incremental compilation for annotation processors (kapt)
kapt.incremental.apt=true
